# Generated by Django 3.1 on 2020-11-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع')),
                ('context', models.TextField(verbose_name='متن اطلاعیه')),
                ('student_page', models.BooleanField(verbose_name='در پنل دانش آموزان نشان داده شود؟')),
                ('main_page', models.BooleanField(verbose_name='در صفحه اصلی نشان داده شود؟')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
            },
        ),
    ]
