# Generated by Django 3.1 on 2020-11-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20201107_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='extra_data',
            field=models.JSONField(default=dict, verbose_name='اطلاعات'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='extra_data',
            field=models.JSONField(default=dict, verbose_name='اطلاعات'),
        ),
    ]
