# Generated by Django 3.1 on 2020-11-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='انجام شده'),
            preserve_default=False,
        ),
    ]
