# Generated by Django 3.1 on 2020-10-14 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teaching', '0004_auto_20201014_2241'),
        ('user', '0004_auto_20201015_0009'),
        ('mentoring', '0002_assistancecourse_historicalassistancecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAssignedStudyPeriod',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('start_time', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_time', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assistant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.assistant', verbose_name='مشاور')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.student', verbose_name='دانش\u200cآموز')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='teaching.subject', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'historical زمان مطالعه',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AssignedStudyPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('start_time', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_time', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_study_periods', to='user.assistant', verbose_name='مشاور')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_study_periods', to='user.student', verbose_name='دانش\u200cآموز')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teaching.subject', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'زمان مطالعه',
                'verbose_name_plural': 'زمان\u200cهای مطالعه',
            },
        ),
    ]
