# Generated by Django 3.1 on 2020-10-24 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('mentoring', '0003_assignedstudyperiod_historicalassignedstudyperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancecourse',
            name='purchase_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 24, 9, 56, 40, 419971, tzinfo=utc), verbose_name='تاریخ خرید دوره'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancecourse',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_course', to='financial.transaction', verbose_name='تراکنش پرداختی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassistancecourse',
            name='purchase_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 24, 9, 57, 26, 158185, tzinfo=utc), verbose_name='تاریخ خرید دوره'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassistancecourse',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial.transaction', verbose_name='تراکنش پرداختی'),
        ),
    ]
