# Generated by Django 3.1 on 2020-10-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_auto_20201024_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancepackage',
            name='description',
            field=models.TextField(verbose_name='معرفی بسته مشاوره'),
        ),
        migrations.AlterField(
            model_name='historicalassistancepackage',
            name='description',
            field=models.TextField(verbose_name='معرفی بسته مشاوره'),
        ),
    ]
