# Generated by Django 3.1 on 2020-10-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_auto_20201024_1327'),
        ('mentoring', '0005_auto_20201024_1421'),
    ]

    operations = [
    ]
