# Generated by Django 3.1 on 2020-11-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0006_merge_20201024_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedstudyperiod',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='historicalassignedstudyperiod',
            name='subject',
        ),
        migrations.AddField(
            model_name='assignedstudyperiod',
            name='description',
            field=models.TextField(default='desc', verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedstudyperiod',
            name='title',
            field=models.CharField(default='tite', max_length=100, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassignedstudyperiod',
            name='description',
            field=models.TextField(default='title', verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassignedstudyperiod',
            name='title',
            field=models.CharField(default='title', max_length=100, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
