# Generated by Django 3.1 on 2020-10-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_coursesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesession',
            options={'verbose_name': 'جلسه ی کلاس', 'verbose_name_plural': 'جلسه\u200cهای کلاس'},
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='teaching.course', verbose_name='کلاس'),
        ),
    ]
