# Generated by Django 3.1 on 2020-10-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201015_0009'),
        ('teaching', '0004_auto_20201014_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teaching.course', verbose_name='کلاس'),
        ),
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_time', models.DateField(verbose_name='تاریخ خرید دوره')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='teaching.course', verbose_name='کلاس خریداری شده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.student', verbose_name='خریدار کلاس')),
            ],
            options={
                'verbose_name': 'عضویت کلاس',
                'verbose_name_plural': 'عضویت های کلاس',
            },
        ),
    ]
