# Generated by Django 3.1 on 2020-10-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_auto_20201016_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(choices=[('دهم', 'دهم'), ('یازدهم', 'یازدهم'), ('دوازدهم', 'دوازدهم')], max_length=15, verbose_name='پایه'),
        ),
    ]
