# Generated by Django 3.1 on 2020-10-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('teaching', '0005_auto_20201016_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_subscription', to='financial.transaction', verbose_name='تراکنش پرداختی'),
            preserve_default=False,
        ),
    ]
