# Generated by Django 3.1 on 2020-11-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0006_auto_20201026_0152'),
        ('teaching', '0006_coursesubscription_transaction'),
    ]

    operations = [
    ]
