# Generated by Django 3.1 on 2020-11-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0008_historicalsessionattendance_sessionattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skyroom_id',
            field=models.IntegerField(default=0, help_text='این فیلد برای اینکه دانش\u200cآموزان بتوانند به کلاس وارد شوند الزامی\u200cاست!', verbose_name='آیدی اتاق اسکای\u200cروم'),
            preserve_default=False,
        ),
    ]
