# Generated by Django 3.1 on 2020-11-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0009_course_skyroom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='skyroom_id',
        ),
        migrations.AddField(
            model_name='course',
            name='skyroom_name',
            field=models.CharField(default='salam', help_text='این فیلد برای اینکه دانش\u200cآموزان بتوانند به کلاس وارد شوند الزامی\u200cاست!', max_length=50, verbose_name='نام اتاق اسکای\u200cروم'),
            preserve_default=False,
        ),
    ]
