# Generated by Django 3.1 on 2020-11-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0010_auto_20201123_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsessionattendance',
            name='skyroom_login_url',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='skyroom_login_url',
            field=models.CharField(max_length=1024),
        ),
    ]
