# Generated by Django 3.1 on 2020-11-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0011_auto_20201123_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubscription',
            name='purchase_time',
        ),
        migrations.RemoveField(
            model_name='coursesubscription',
            name='transaction',
        ),
    ]
