# Generated by Django 3.1 on 2020-10-16 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistancediscount',
            options={'verbose_name': 'تخفیف مشاوره', 'verbose_name_plural': 'تخفیف های مشاوره'},
        ),
        migrations.AlterModelOptions(
            name='coursediscount',
            options={'verbose_name': 'تخفیف کلاس', 'verbose_name_plural': 'تخفیف های کلاس'},
        ),
        migrations.AlterModelOptions(
            name='historicalassistancediscount',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical تخفیف مشاوره'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoursediscount',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical تخفیف کلاس'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='historicalassistancediscount',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='historicalcoursediscount',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
    ]
