# Generated by Django 3.1 on 2020-10-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounting', '0002_auto_20201016_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='historicalassistancediscount',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=5, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='historicalcoursediscount',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=5, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=5, verbose_name='کد'),
        ),
    ]
