# Generated by Django 3.1 on 2020-10-18 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201017_1253'),
        ('discounting', '0005_auto_20201017_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='گیرنده کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='historicalassistancediscount',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='historicalassistancediscount',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='historicalassistancediscount',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.student', verbose_name='گیرنده کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='historicalcoursediscount',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='historicalcoursediscount',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='historicalcoursediscount',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.student', verbose_name='گیرنده کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.student', verbose_name='گیرنده کد تخفیف'),
        ),
    ]
