# Generated by Django 3.1 on 2020-10-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounting', '0002_auto_20201016_1538'),
        ('discounting', '0006_auto_20201018_1425'),
    ]

    operations = [
    ]
