# Generated by Django 3.1 on 2020-10-10 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantIntroductionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='لینک فیلم')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introduction_videos', to='user.assistant', verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'فیلم معرفی مشاور',
                'verbose_name_plural': 'فیلم\u200cهای معرفی مشاور',
            },
        ),
    ]
