# Generated by Django 3.1 on 2020-10-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducing', '0002_teacherintroductionvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantintroductionvideo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='teacherintroductionvideo',
            name='link',
        ),
        migrations.AddField(
            model_name='assistantintroductionvideo',
            name='aparat_id',
            field=models.CharField(default='shit', max_length=20, verbose_name='آیدی آپارات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantintroductionvideo',
            name='embed_hash',
            field=models.CharField(default='shit', max_length=10, verbose_name='هش ویدیو'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherintroductionvideo',
            name='aparat_id',
            field=models.CharField(default='shit', max_length=20, verbose_name='آیدی آپارات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherintroductionvideo',
            name='embed_hash',
            field=models.CharField(default='shit', max_length=10, verbose_name='هش ویدیو'),
            preserve_default=False,
        ),
    ]
