# Generated by Django 3.1 on 2020-10-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201015_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='nationality_code',
            field=models.CharField(default='tgfgdds', max_length=10, verbose_name='شماره شناسنامه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='nationality_code',
            field=models.CharField(default='tgfgdds', max_length=10, verbose_name='شماره شناسنامه'),
            preserve_default=False,
        ),
    ]
