# Generated by Django 3.1 on 2020-10-17 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201017_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='gender',
            field=models.CharField(choices=[('female', 'زن'), ('male', 'مرد')], default='female', max_length=6, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='school',
            field=models.CharField(default='my-school', max_length=50, verbose_name='مدرسه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'زن'), ('male', 'مرد')], default='female', max_length=6, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='school', max_length=50, verbose_name='مدرسه'),
            preserve_default=False,
        ),
    ]
