# Generated by Django 3.1 on 2020-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201017_1253'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assistant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='assistant',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='short_description',
            field=models.TextField(default='nice', verbose_name='توضیحات کوتاه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassistant',
            name='profile_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='historicalassistant',
            name='short_description',
            field=models.TextField(default='nice', verbose_name='توضیحات کوتاه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='profile_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='profile_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='short_description',
            field=models.TextField(default='nice', verbose_name='توضیحات کوتاه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='short_description',
            field=models.TextField(default='nice', verbose_name='توضیحات کوتاه'),
            preserve_default=False,
        ),
    ]
