# Generated by Django 3.1 on 2020-11-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201019_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassistant',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=20),
            preserve_default=False,
        ),
    ]
