# Generated by Django 3.1 on 2020-11-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201103_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='home_page_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='عکس صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='در برترین اساتید باشد؟'),
        ),
        migrations.AddField(
            model_name='historicalassistant',
            name='home_page_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='عکس صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='historicalassistant',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='در برترین اساتید باشد؟'),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='home_page_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='عکس صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='در برترین اساتید باشد؟'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='home_page_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='عکس صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='در برترین اساتید باشد؟'),
        ),
    ]
