# Generated by Django 3.1 on 2020-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201123_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='home_page_image',
            field=models.FileField(blank=True, help_text='اگر این فیلد خالی باشد عکس پروفایل در صفحه اصلی(در صورت در برترین مشاورین بودن) نمایش داده خواهد شد.', null=True, upload_to='', verbose_name='عکس صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='در برترین مشاورین باشد؟'),
        ),
        migrations.AlterField(
            model_name='historicalassistant',
            name='home_page_image',
            field=models.TextField(blank=True, help_text='اگر این فیلد خالی باشد عکس پروفایل در صفحه اصلی(در صورت در برترین مشاورین بودن) نمایش داده خواهد شد.', max_length=100, null=True, verbose_name='عکس صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='historicalassistant',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='در برترین مشاورین باشد؟'),
        ),
        migrations.AlterField(
            model_name='historicalteacher',
            name='home_page_image',
            field=models.TextField(blank=True, help_text='اگر این فیلد خالی باشد عکس پروفایل در صفحه اصلی(در صورت در برترین اساتید بودن) نمایش داده خواهد شد.', max_length=100, null=True, verbose_name='عکس صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='home_page_image',
            field=models.FileField(blank=True, help_text='اگر این فیلد خالی باشد عکس پروفایل در صفحه اصلی(در صورت در برترین اساتید بودن) نمایش داده خواهد شد.', null=True, upload_to='', verbose_name='عکس صفحه اصلی'),
        ),
    ]
