# Generated by Django 3.1 on 2020-11-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konkour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام کنکور')),
                ('date', models.DateTimeField(verbose_name='تاریخ برگزاری')),
                ('field', models.CharField(choices=[('ریاضی-فیزیک', 'ریاضی-فیزیک'), ('تجربی', 'تجربی'), ('انسانی', 'انسانی'), ('هنر', 'هنر'), ('زبان', 'زبان')], max_length=20, verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'کنکور',
                'verbose_name_plural': 'کنکورها',
            },
        ),
    ]
